layout_spectrum: 0.235768
color:
  saturation: 0.4591837
  brandStrength: 1
  lightness: 0.7717508
  brandColors:
    - '#0E0E0C'
    - '#FFFFFF'
    - '#5D5C5B'
    - '#91776E'
    - '#E0C6BD'
  rhythmicContrast: 1
typography_spectrum: 0.5912997
name: Sudeep Gohil
